=== ItsMeParker/Twin_Cites_Website/Connor_Database_XML/fet15021296.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="database">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="country"/>
      </xs:sequence>
      <xs:attribute name="databaseName" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  
  <!-- START OF COUNTRY DEFINITION -->
  
  <xs:element name="country">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="countryName"/>
        <xs:element ref="population"/>
        <xs:element ref="nationalLanguage"/>
        <xs:element ref="gdp"/>
        <xs:element ref="wikiLink"/>
        <xs:element ref="city"/>
      </xs:sequence>
      <xs:attribute name="countryName" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="countryName" type="xs:string"/>
  <xs:element name="nationalLanguage" type="xs:NCName"/>
  
  <!-- START OF CITY DEFINITION -->
  
  <xs:element name="city">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="geocodeLatitude"/>
        <xs:element ref="geocodeLongitude"/>
        <xs:element ref="woeid"/>
        <xs:element ref="countyState"/>
        <xs:element ref="population"/>
        <xs:element ref="area"/>
        <xs:element ref="currency"/>
        <xs:element ref="primaryLanguage"/>
        <xs:element ref="wikiLink"/>
        <xs:element ref="attractions"/>
        <xs:element ref="weather"/>
        <xs:element ref="forecast"/>
      </xs:sequence>
      <xs:attribute name="cityName" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="woeid" type="xs:integer"/>
  <xs:element name="countyState" type="xs:NCName"/>
  <xs:element name="area" type="xs:integer"/>
  <xs:element name="currency" type="xs:NCName"/>
  <xs:element name="primaryLanguage" type="xs:NCName"/>
  
  <!-- START OF ATTRACTIONS DEFINITION -->
  
  <xs:element name="attractions">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="localAttraction"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="localAttraction">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="attractionName"/>
        <xs:element ref="geocodeLatitude"/>
        <xs:element ref="geocodeLongitude"/>
        <xs:element ref="website"/>
        <xs:element ref="rating"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="attractionName" type="xs:string"/>
  <xs:element name="website" type="xs:anyURI"/>
  
  <!-- START OF WEATHER DEFINITION -->
  
  <xs:element name="weather">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lastChecked"/>
        <xs:element ref="published_at"/>
        <xs:element ref="current_temp"/>
        <xs:element ref="weatherCode"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="current_temp" type="xs:integer"/>
  
  <!-- START OF FORECAST DEFINITION -->
  
  <xs:element name="forecast">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="date"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="date">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="weatherCode"/>
        <xs:element ref="tempHigh"/>
        <xs:element ref="tempLow"/>
      </xs:sequence>
      <xs:attribute name="dateOffset" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tempHigh" type="xs:integer"/>
  <xs:element name="tempLow" type="xs:integer"/>
  <xs:element name="population" type="xs:integer"/>
  <xs:element name="wikiLink" type="xs:anyURI"/>
  <xs:element name="weatherCode" type="xs:string"/>
  
  <!-- MY OWN ELEMENT DEFINITIONS -->  
  
  <xs:element name="geocodeLatitude" type="latType"/>
  <xs:element name="geocodeLongitude" type="lonType"/>
  <xs:element name="gdp" type="gdpType"/>
  <xs:element name="rating" type="ratingType"/>
  <xs:element name="lastChecked" type="sqlDateTimeType"/>
  <xs:element name="published_at" type="sqlDateTimeType"/>
  
  <!-- MY OWN TYPE DEFINITIONS -->  
  
  <xs:simpleType name="latType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="-90.000000"></xs:minInclusive>
      <xs:maxInclusive value="90.000000"></xs:maxInclusive>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="lonType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="-180.000000"></xs:minInclusive>
      <xs:maxInclusive value="180.000000"></xs:maxInclusive>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="gdpType">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]+[.][0-9]+[ ]trillion)"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="ratingType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(-1[.]0)|([0-4][.][0-9])|(5[.]0)"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="sqlDateTimeType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{1,4}-[0-9]{1,2}-[0-9]{1,2} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2}"/>
    </xs:restriction>
  </xs:simpleType> 
  
</xs:schema>

=== ItsMeParker/Twin_Cites_Website/assignment/source/database_xml_xsd/fet15021296.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
- data take from database at time: Mar 07, 2018 at 07:20 PM
-->

<!--
- Database: 'fet15021296'
-->
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="fet15021296.xsd" databaseName="fet15021296">
    <country countryName="United Kingdom"> 
        <countryName>United Kingdom</countryName>
        <population>65640000</population>
        <nationalLanguage>English</nationalLanguage>
        <gdp>2.619 trillion</gdp>
        <wikiLink>www.wikipedia.com/UnitedKingdom</wikiLink>

        <city cityName="leicester">     
            <geocodeLatitude>52.636959</geocodeLatitude>
            <geocodeLongitude>1.129040</geocodeLongitude>
            <woeid>26062</woeid>
            <countyState>Leicestershire</countyState>
            <population>329839</population>
            <area>28</area>
            <currency>Pounds</currency>
            <primaryLanguage>English</primaryLanguage>
            <wikiLink>https://en.wikipedia.org/wiki/Leicester</wikiLink>

            <attractions>
                <localAttraction>
                    <attractionName>Ramada Encore Leicester City Centre</attractionName>
                    <geocodeLatitude>52.634667</geocodeLatitude>
                    <geocodeLongitude>-1.129265</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Ramada+Encore+Leicester+City+Centre</website>
                    <rating>4.0</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Mercure Leicester The Grand Hotel</attractionName>
                    <geocodeLatitude>52.633197</geocodeLatitude>
                    <geocodeLongitude>-1.129889</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Mercure+Leicester+The+Grand+Hotel</website>
                    <rating>3.9</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Nationwide</attractionName>
                    <geocodeLatitude>52.634217</geocodeLatitude>
                    <geocodeLongitude>-1.132492</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Nationwide</website>
                    <rating>2.4</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Clarks</attractionName>
                    <geocodeLatitude>52.636213</geocodeLatitude>
                    <geocodeLongitude>-1.132669</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Clarks</website>
                    <rating>4.0</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Cafe Roma</attractionName>
                    <geocodeLatitude>52.634561</geocodeLatitude>
                    <geocodeLongitude>-1.130582</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Cafe+Roma</website>
                    <rating>4.6</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Shoe Zone</attractionName>
                    <geocodeLatitude>52.634842</geocodeLatitude>
                    <geocodeLongitude>-1.133879</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Shoe+Zone</website>
                    <rating>3.5</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Subway</attractionName>
                    <geocodeLatitude>52.636273</geocodeLatitude>
                    <geocodeLongitude>-1.129227</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Subway</website>
                    <rating>3.3</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>The City Rooms</attractionName>
                    <geocodeLatitude>52.633750</geocodeLatitude>
                    <geocodeLongitude>-1.134150</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=The+City+Rooms</website>
                    <rating>4.4</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Sports Direct</attractionName>
                    <geocodeLatitude>52.636211</geocodeLatitude>
                    <geocodeLongitude>-1.132487</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Sports+Direct</website>
                    <rating>4.0</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>The Hyde Apartments</attractionName>
                    <geocodeLatitude>52.635125</geocodeLatitude>
                    <geocodeLongitude>-1.126161</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=The+Hyde+Apartments</website>
                    <rating>5.0</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Pearson Professional Centres - UK Leicester</attractionName>
                    <geocodeLatitude>52.635459</geocodeLatitude>
                    <geocodeLongitude>-1.128278</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Pearson+Professional+Centres+-+UK+Leicester</website>
                    <rating>3.1</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Primark</attractionName>
                    <geocodeLatitude>52.636642</geocodeLatitude>
                    <geocodeLongitude>-1.130773</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Primark</website>
                    <rating>3.9</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>The Dental Suite</attractionName>
                    <geocodeLatitude>52.633603</geocodeLatitude>
                    <geocodeLongitude>-1.129743</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=The+Dental+Suite</website>
                    <rating>4.2</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Ann Summers</attractionName>
                    <geocodeLatitude>52.636400</geocodeLatitude>
                    <geocodeLongitude>-1.131804</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Ann+Summers</website>
                    <rating>3.3</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Coventry Building Society Leicester</attractionName>
                    <geocodeLatitude>52.635979</geocodeLatitude>
                    <geocodeLongitude>-1.132296</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Coventry+Building+Society+Leicester</website>
                    <rating>-1.0</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Dorothy Perkins</attractionName>
                    <geocodeLatitude>52.635654</geocodeLatitude>
                    <geocodeLongitude>-1.132394</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Dorothy+Perkins</website>
                    <rating>4.2</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Music Junkie</attractionName>
                    <geocodeLatitude>52.637906</geocodeLatitude>
                    <geocodeLongitude>-1.128230</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Music+Junkie</website>
                    <rating>4.7</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>William H Brown Estate Agents in Leicester</attractionName>
                    <geocodeLatitude>52.634688</geocodeLatitude>
                    <geocodeLongitude>-1.130629</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=William+H+Brown+Estate+Agents+in+Leicester</website>
                    <rating>2.0</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>Boots Opticians</attractionName>
                    <geocodeLatitude>52.635103</geocodeLatitude>
                    <geocodeLongitude>-1.131820</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=Boots+Opticians</website>
                    <rating>4.0</rating>
                </localAttraction>
                <localAttraction>
                    <attractionName>The Works</attractionName>
                    <geocodeLatitude>52.634790</geocodeLatitude>
                    <geocodeLongitude>-1.131712</geocodeLongitude>
                    <website>https://www.google.co.uk/search?q=The+Works</website>
                    <rating>4.1</rating>
                </localAttraction>
            </attractions>

            <weather>
                <lastChecked>2018-03-06 14:18:53</lastChecked>
                <published_at>2018-03-06 13:00:00</published_at>
                <current_temp>44</current_temp>
                <weatherCode>cloudy</weatherCode>
            </weather>

            <forecast>
                <date  dateOffset="0">
                    <weatherCode>showers</weatherCode>
                    <tempHigh>46</tempHigh>
                    <tempLow>37</tempLow>
                </date>
                <date dateOffset="1">
                    <weatherCode>mostly cloudy (day)</weatherCode>
                    <tempHigh>47</tempHigh>
                    <tempLow>34</tempLow>
                </date>
                <date dateOffset="2">
